version: '3.5'
services:
  nhsd.buyingcatalogue.identity.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/identity-api:${TAG:-latest}
    container_name: identity_api
    build: 
      context: .
      dockerfile: src/NHSD.BuyingCatalogue.Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ISSUERURL=http://localhost:8070
      - CLIENTS__0__ALLOWEDGRANTTYPES=ClientCredentials
    networks:
      - nhsd_bcnetwork
    ports:
      - "8070:80"

  nhsd.buyingcatalogue.identity.api.sampleresource:
    image: ${REGISTRY:-nhsd}/buying-catalogue/identity/api-sampleresource:${TAG:-latest}
    container_name: identity_api_sample_resource
    build: 
        context: .
        dockerfile: samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - nhsd_bcnetwork
    ports:
        - "8071:80"
    
networks: 
  nhsd_bcnetwork:
    name: nhsd_bcnetwork
    driver: bridge