version: '3.5'
services:
  nhsd.buyingcatalogue.identity.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/identity-api:${TAG:-latest}
    container_name: identity_api
    build: 
      context: .
      dockerfile: src/NHSD.BuyingCatalogue.Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CLIENTS__0__REDIRECTURLS__0=http://localhost:8072/signin-oidc
    networks:
      - nhsd_bcnetwork
    ports:
      - "8070:80"

  nhsd.buyingcatalogue.identity.api.sampleresource:
    image: ${REGISTRY:-nhsd}/buying-catalogue/identity/api-sampleresource:${TAG:-latest}
    container_name: identity_api_sample_resource
    build: 
        context: .
        dockerfile: samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - AUTHORITY=http://host.docker.internal:8070
    networks:
        - nhsd_bcnetwork
    ports:
        - "8071:80"
        
  nhsd.buyingcatalogue.identity.api.samplemvcclient:
    image: ${REGISTRY:-nhsd}/buying-catalogue/identity/api-samplemvcclient:${TAG:-latest}
    container_name: identity_api_sample_mvc_client
    build: 
        context: .
        dockerfile: samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - AUTHORITY=http://host.docker.internal:8070
        - SAMPLERESOURCEURL=http://host.docker.internal:8071/Identity
    networks:
        - nhsd_bcnetwork
    ports:
        - "8072:80"
    
networks: 
  nhsd_bcnetwork:
    name: nhsd_bcnetwork
    driver: bridge